vich_uploader:
    db_driver: orm

    mappings:
       product_images:
           uri_prefix: /assets/images/slider
           upload_destination: '%kernel.project_dir%/public/assets/images/slider'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
